### ISSUE TITLE
Release TODO

### ISSUE THREAD

**Issue by stkptr** [stkptr/gdsodium#1]
## Housekeeping

- [x] Unit testing
- [-] Coverage testing
  - [ ] Coverage testing in CI

## Features

- [ ] Generic hash
- [ ] Secret stream
- [ ] Box
- [ ] Secret box
- [x] Key exchange
- [x] Signing
- [ ] AEAD
  - [x] Implementation 
  - [ ] Unit tests
- [ ] Password hashing
  - [x] Implementation 
  - [ ] Unit tests
- [ ] Key derivation (HKDF)
  - [x] SHA256
  - [ ] SHA512
- [ ] CSPRNG
- [ ] Big numbers (comparisons, basic operations)
- [ ] Padding
- [ ] Ciphers
- [ ] Short hash
- [ ] Authentication
- [ ] Curve math
